"""
Turns a scan report dict into HTML or PDF, for the /scan/{id}/export
endpoint. JSON export needs no work (the DB already stores it as JSON) so
it isn't handled here.
"""

import html
import json


def _severity_color(text: str) -> str:
    t = (text or "").lower()
    if t in ("critical",):
        return "#7f1d1d"
    if t in ("high",):
        return "#b91c1c"
    if t in ("medium",):
        return "#b45309"
    if t in ("low",):
        return "#0369a1"
    return "#374151"


def generate_html_report(report: dict) -> str:
    score = report.get("score", {})
    ssl = report.get("ssl", {})
    tech = report.get("technology", {})
    headers = report.get("headers", {})
    nmap = report.get("nmap", {})
    nikto = report.get("nikto", {})
    nessus = report.get("nessus", {})

    def esc(v):
        return html.escape(str(v))

    header_findings_html = "".join(
        f"<li><span class='sev' style='background:{_severity_color(f.get('severity'))}'>"
        f"{esc(f.get('severity'))}</span> {esc(f.get('title'))} — {esc(f.get('description'))}</li>"
        for f in headers.get("findings", [])
    ) or "<li>No missing security headers detected.</li>"

    ports_html = "".join(
        f"<li>{esc(p.get('port'))}/tcp {esc(p.get('state'))} — {esc(p.get('service'))} {esc(p.get('version',''))}</li>"
        for p in nmap.get("open_ports", [])
    ) or "<li>No open ports detected (or nmap unavailable).</li>"

    nikto_html = "".join(
        f"<li>{esc(f.get('message', f))}</li>" for f in nikto.get("findings", [])
    ) or f"<li>{esc(nikto.get('error') or 'No issues reported.')}</li>"

    nessus_html = "".join(
        f"<li><span class='sev' style='background:{_severity_color(f.get('severity'))}'>"
        f"{esc(f.get('severity'))}</span> {esc(f.get('name'))}</li>"
        for f in nessus.get("findings", [])
    ) or f"<li>{esc(nessus.get('error') or 'No vulnerabilities reported.')}</li>"

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>SecureLens Report — {esc(report.get('target'))}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; max-width: 800px; margin: 40px auto; color: #111827; }}
  h1 {{ margin-bottom: 0; }}
  .subtitle {{ color: #6b7280; margin-top: 4px; }}
  .score-badge {{ display: inline-block; font-size: 2.5rem; font-weight: 700; padding: 8px 24px; border-radius: 12px; color: white; background: #111827; }}
  .grade-A, .grade-B {{ background: #15803d; }}
  .grade-C {{ background: #b45309; }}
  .grade-D, .grade-F {{ background: #b91c1c; }}
  section {{ margin-top: 28px; }}
  h2 {{ border-bottom: 2px solid #e5e7eb; padding-bottom: 6px; }}
  ul {{ padding-left: 20px; }}
  li {{ margin-bottom: 6px; }}
  .sev {{ color: white; font-size: 0.75rem; padding: 2px 8px; border-radius: 4px; margin-right: 6px; }}
  table {{ width: 100%; border-collapse: collapse; }}
  td {{ padding: 6px 0; border-bottom: 1px solid #f3f4f6; }}
  footer {{ margin-top: 40px; color: #9ca3af; font-size: 0.8rem; }}
</style>
</head>
<body>
  <h1>SecureLens Security Report</h1>
  <p class="subtitle">Target: {esc(report.get('target'))}</p>

  <div class="score-badge grade-{esc(score.get('grade','F'))}">
    {esc(score.get('overall_score','?'))}/100 — Grade {esc(score.get('grade','?'))}
  </div>
  <p>Risk level: <strong>{esc(score.get('risk_level','Unknown'))}</strong></p>

  <section>
    <h2>SSL / TLS</h2>
    <table>
      <tr><td>Enabled</td><td>{esc(ssl.get('ssl_enabled'))}</td></tr>
      <tr><td>Issuer</td><td>{esc(ssl.get('issuer','Unknown'))}</td></tr>
      <tr><td>Expires</td><td>{esc(ssl.get('expires_on','Unknown'))}</td></tr>
      <tr><td>Days remaining</td><td>{esc(ssl.get('days_remaining','Unknown'))}</td></tr>
    </table>
  </section>

  <section>
    <h2>Technology Detected</h2>
    <table>
      <tr><td>Server</td><td>{esc(tech.get('server','Unknown'))}</td></tr>
      <tr><td>Framework</td><td>{esc(tech.get('framework','Unknown'))}</td></tr>
      <tr><td>CDN</td><td>{esc(tech.get('cdn','Unknown'))}</td></tr>
    </table>
  </section>

  <section>
    <h2>Security Headers</h2>
    <ul>{header_findings_html}</ul>
  </section>

  <section>
    <h2>Open Ports (nmap)</h2>
    <ul>{ports_html}</ul>
  </section>

  <section>
    <h2>Web Server Findings (nikto)</h2>
    <ul>{nikto_html}</ul>
  </section>

  <section>
    <h2>Vulnerability Scan (nessus)</h2>
    <ul>{nessus_html}</ul>
  </section>

  <footer>Generated by SecureLens. Report data below for reference.</footer>
</body>
</html>"""


def generate_pdf_report(report: dict) -> bytes:
    """Renders a simple, readable PDF using fpdf2 (pure-Python, no system
    dependency like wkhtmltopdf/Chromium needed)."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    score = report.get("score", {})

    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "SecureLens Security Report", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Target: {report.get('target', 'Unknown')}", ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(
        0, 10,
        f"Score: {score.get('overall_score', '?')}/100   "
        f"Grade: {score.get('grade', '?')}   "
        f"Risk: {score.get('risk_level', '?')}",
        ln=True,
    )
    pdf.ln(4)

    def section(title, lines):
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 9, title, ln=True)
        pdf.set_font("Helvetica", "", 10)
        if not lines:
            lines = ["(none)"]
        for line in lines:
            # multi_cell leaves x at the right edge after wrapping, so
            # reset to the left margin before every call or subsequent
            # calls raise "Not enough horizontal space".
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 6, f"  - {line}")
        pdf.ln(2)

    ssl = report.get("ssl", {})
    section("SSL / TLS", [
        f"Enabled: {ssl.get('ssl_enabled')}",
        f"Issuer: {ssl.get('issuer', 'Unknown')}",
        f"Expires: {ssl.get('expires_on', 'Unknown')} ({ssl.get('days_remaining', '?')} days remaining)",
    ])

    tech = report.get("technology", {})
    section("Technology Detected", [
        f"Server: {tech.get('server', 'Unknown')}",
        f"Framework: {tech.get('framework', 'Unknown')}",
        f"CDN: {tech.get('cdn', 'Unknown')}",
    ])

    headers = report.get("headers", {})
    section(
        "Security Header Findings",
        [f"[{f.get('severity')}] {f.get('title')}: {f.get('description')}"
         for f in headers.get("findings", [])],
    )

    nmap = report.get("nmap", {})
    section(
        "Open Ports (nmap)",
        [f"{p.get('port')}/tcp {p.get('state')} - {p.get('service')} {p.get('version', '')}"
         for p in nmap.get("open_ports", [])],
    )

    nikto = report.get("nikto", {})
    section(
        "Web Server Findings (nikto)",
        [str(f.get("message", f)) for f in nikto.get("findings", [])],
    )

    nessus = report.get("nessus", {})
    section(
        "Vulnerability Scan (nessus)",
        [f"[{f.get('severity')}] {f.get('name')}" for f in nessus.get("findings", [])],
    )

    return bytes(pdf.output())


if __name__ == "__main__":
    with open("sample_report.json") as f:
        sample = json.load(f)
    print(generate_html_report(sample)[:500])
